### ISSUE TITLE
Add SQL-Query to new Mojolicious plattform date picker

### ISSUE THREAD

**Issue by sweitmann** [sl-community/rmac#11]
Hi Axel,

First of all; Thank you for your excellent support and all your contributions helping us move this beautiful free SQL-Ledger accounting software project to its next level. 

I really like and admire the way you have added a Mojolicious layer creating a new well structured and clean base for contributing ancillary code to the project.

In regard to the new date picker in 'Export--GoBD' and 'Export--Preliminary VAT Return' I would simply like to ask you to make some minor adjustments so that they look, feel and work the same way as all other previous date pickers available in SQL-Ledger

a.) Please adjust the years currently offered in "%= include '_partial/date_interval_picker', offer_years =>" to be defined by the actual years for which there is accounting data available in the database acc_trans table. 

b.) Kindly remove the expendable text "...or..." between the fields where you have the option to enter the date manually or use the date picker:
![Screenshot from 2019-09-05 04-43-01](https://user-images.githubusercontent.com/100664/64307906-cdb95f80-cf97-11e9-8980-436e5592b2d7.png)

c.) And please change the wording from "Until now" to "Current":
![Screenshot from 2019-09-05 04-43-01](https://user-images.githubusercontent.com/100664/64308738-95675080-cf9a-11e9-97e5-441216ec0b9a.png)

Regards

**Comment by Salvor42** [comment]
Should now behave as expected.
