### ISSUE TITLE
GoBD-Export

### ISSUE THREAD

**Issue by sweitmann** [sl-community/rmac#13]
Hi Axel,

We have an issue with the GoBD-Export. I was contacted by an auditor from the German tax authorities who informed me that the journal.csv column "Buchungstext" does not have the correct content. Instead the column "Buchungstext" currently shows the account name (Kontenbezeichnung). 

Could you please adjust the 'Export--GoBD' feature, so that 

a.) the content currently exported into the column "Buchungstext" is placed in a new column to the right of the column "Kontonummer" with the header "Kontenbezeichung" and

b.) the column "Buchungstext" is filled with the respective SQL-Ledger database (AR, AP or GL) field "description" instead. 

Regards

**Comment by Salvor42** [comment]
Should work now as expected.
